apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "webservice-chart.fullname" . }}
  labels:
    app: {{ template "webservice-chart.name" . }}
    chart: {{ template "webservice-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "webservice-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "webservice-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.image.credentials }}
      imagePullSecrets:
        - name: {{ template "webservice-chart.image.pullSecret.name" . }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ template "webservice-chart.service.internalPort" . }}
              protocol: TCP
          {{- with .Values.monitoring.livenessProbe }}
          livenessProbe:
{{ toYaml . | trimSuffix "\n" | indent 12 }}
          {{- end }}
          {{- with .Values.monitoring.readinessProbe }}
          readinessProbe:
{{ toYaml . | trimSuffix "\n" | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
